// Shared with the browser; this module must stay dependency-free.
export const ADMIN_ROUTES: Readonly<Record<string, string>> = {
  "GET session": "admin.access",
  "GET overview": "dashboard.read",
  "GET stats": "dashboard.read",
  "GET dashboard": "dashboard.read",
  "GET users": "users.read",
  "GET quizzes": "quizzes.read",
  "GET support": "support.read",
  "GET reports": "reports.read",
  "GET finances": "finance.read",
  "GET promocodes": "promocodes.manage",
  "GET audit": "audit.read",
  "POST update-user": "staff.manage",
  "POST user-status": "users.manage",
  "POST block-user": "users.manage",
  "POST moderate-quiz": "quizzes.moderate",
  "POST quiz-moderation": "quizzes.moderate",
  "POST support/reply": "support.manage",
  "POST support-reply": "support.manage",
  "POST support/update-status": "support.manage",
  "POST support-status": "support.manage",
  "POST reports/update": "reports.manage",
  "POST report-status": "reports.manage",
  "POST grant-pro": "billing.grant",
  "POST promocode-create": "promocodes.manage",
  "POST promocode-toggle": "promocodes.manage",
  "POST promocode-delete": "promocodes.manage",
};
export const ADMIN_PAGES: Readonly<Record<string, string>> = {
  "/admin": "dashboard.read",
  "/admin/users": "users.read",
  "/admin/quizzes": "quizzes.read",
  "/admin/reports": "reports.read",
  "/admin/support": "support.read",
  "/admin/finances": "finance.read",
  "/admin/promocodes": "promocodes.manage",
};
export const ROLE_PERMISSIONS = {
  owner: [
    "admin.access",
    "dashboard.read",
    "users.read",
    "users.manage",
    "quizzes.read",
    "quizzes.manage",
    "quizzes.moderate",
    "reports.read",
    "reports.manage",
    "subscriptions.read",
    "subscriptions.manage",
    "support.read",
    "support.manage",
    "finance.read",
    "promocodes.manage",
    "notifications.manage",
    "settings.manage",
    "audit.read",
    "staff.manage",
    "billing.grant",
  ],
  admin: [
    "admin.access",
    "dashboard.read",
    "users.read",
    "users.manage",
    "quizzes.read",
    "quizzes.manage",
    "quizzes.moderate",
    "reports.read",
    "reports.manage",
    "subscriptions.read",
    "subscriptions.manage",
    "support.read",
    "support.manage",
    "finance.read",
    "promocodes.manage",
    "notifications.manage",
    "audit.read",
    "billing.grant",
  ],
  moderator: [
    "admin.access",
    "dashboard.read",
    "users.read",
    "quizzes.read",
    "quizzes.moderate",
    "reports.read",
    "reports.manage",
    "audit.read",
  ],
  support: [
    "admin.access",
    "dashboard.read",
    "users.read",
    "quizzes.read",
    "subscriptions.read",
    "support.read",
    "support.manage",
    "notifications.manage",
  ],
} as const;
export function isAccountBlocked(
  status?: string | null,
  until?: string | null,
  now = Date.now(),
): boolean {
  return (
    status === "blocked" ||
    (status === "temporarily_blocked" &&
      (!until ||
        !Number.isFinite(Date.parse(until)) ||
        Date.parse(until) > now))
  );
}
