export interface ColorConfig {
  gradient: string;
  bg: string;
  text: string;
  shadow: string;
  glow: string;
  accent: string;
  light: string;
  handle: string;
  border: string;
  ring: string;
}

export const COLOR_CLASSES = {
  blue: {
    gradient: 'from-blue-500 to-blue-600',
    bg: 'bg-blue-500',
    text: 'text-blue-600',
    shadow: 'shadow-blue-500/25',
    glow: 'group-hover:shadow-blue-500/40',
    accent: 'bg-blue-50 border-blue-100',
    light: 'bg-blue-50',
    handle: 'bg-gradient-to-br from-blue-400 to-blue-600',
    border: 'border-blue-400',
    ring: 'ring-blue-100',
  },
  green: {
    gradient: 'from-emerald-500 to-emerald-600',
    bg: 'bg-emerald-500',
    text: 'text-emerald-600',
    shadow: 'shadow-emerald-500/25',
    glow: 'group-hover:shadow-emerald-500/40',
    accent: 'bg-emerald-50 border-emerald-100',
    light: 'bg-emerald-50',
    handle: 'bg-gradient-to-br from-emerald-400 to-emerald-600',
    border: 'border-emerald-400',
    ring: 'ring-emerald-100',
  },
  purple: {
    gradient: 'from-purple-500 to-purple-600',
    bg: 'bg-purple-500',
    text: 'text-purple-600',
    shadow: 'shadow-purple-500/25',
    glow: 'group-hover:shadow-purple-500/40',
    accent: 'bg-purple-50 border-purple-100',
    light: 'bg-purple-50',
    handle: 'bg-gradient-to-br from-purple-400 to-purple-600',
    border: 'border-purple-400',
    ring: 'ring-purple-100',
  },
  yellow: {
    gradient: 'from-amber-500 to-amber-600',
    bg: 'bg-amber-500',
    text: 'text-amber-600',
    shadow: 'shadow-amber-500/25',
    glow: 'group-hover:shadow-amber-500/40',
    accent: 'bg-amber-50 border-amber-100',
    light: 'bg-amber-50',
    handle: 'bg-gradient-to-br from-amber-400 to-amber-600',
    border: 'border-amber-400',
    ring: 'ring-amber-100',
  },
  orange: {
    gradient: 'from-orange-500 to-orange-600',
    bg: 'bg-orange-500',
    text: 'text-orange-600',
    shadow: 'shadow-orange-500/25',
    glow: 'group-hover:shadow-orange-500/40',
    accent: 'bg-orange-50 border-orange-100',
    light: 'bg-orange-50',
    handle: 'bg-gradient-to-br from-orange-400 to-orange-600',
    border: 'border-orange-400',
    ring: 'ring-orange-100',
  },
  gray: {
    gradient: 'from-slate-500 to-slate-600',
    bg: 'bg-slate-500',
    text: 'text-slate-600',
    shadow: 'shadow-slate-500/25',
    glow: 'group-hover:shadow-slate-500/40',
    accent: 'bg-slate-50 border-slate-100',
    light: 'bg-slate-50',
    handle: 'bg-gradient-to-br from-slate-400 to-slate-600',
    border: 'border-slate-400',
    ring: 'ring-slate-100',
  },
  indigo: {
    gradient: 'from-indigo-500 to-indigo-600',
    bg: 'bg-indigo-500',
    text: 'text-indigo-600',
    shadow: 'shadow-indigo-500/25',
    glow: 'group-hover:shadow-indigo-500/40',
    accent: 'bg-indigo-50 border-indigo-100',
    light: 'bg-indigo-50',
    handle: 'bg-gradient-to-br from-indigo-400 to-indigo-600',
    border: 'border-indigo-400',
    ring: 'ring-indigo-100',
  },
  teal: {
    gradient: 'from-teal-500 to-teal-600',
    bg: 'bg-teal-500',
    text: 'text-teal-600',
    shadow: 'shadow-teal-500/25',
    glow: 'group-hover:shadow-teal-500/40',
    accent: 'bg-teal-50 border-teal-100',
    light: 'bg-teal-50',
    handle: 'bg-gradient-to-br from-teal-400 to-teal-600',
    border: 'border-teal-400',
    ring: 'ring-teal-100',
  },
  pink: {
    gradient: 'from-pink-500 to-pink-600',
    bg: 'bg-pink-500',
    text: 'text-pink-600',
    shadow: 'shadow-pink-500/25',
    glow: 'group-hover:shadow-pink-500/40',
    accent: 'bg-pink-50 border-pink-100',
    light: 'bg-pink-50',
    handle: 'bg-gradient-to-br from-pink-400 to-pink-600',
    border: 'border-pink-400',
    ring: 'ring-pink-100',
  },
  cyan: {
    gradient: 'from-cyan-500 to-cyan-600',
    bg: 'bg-cyan-500',
    text: 'text-cyan-600',
    shadow: 'shadow-cyan-500/25',
    glow: 'group-hover:shadow-cyan-500/40',
    accent: 'bg-cyan-50 border-cyan-100',
    light: 'bg-cyan-50',
    handle: 'bg-gradient-to-br from-cyan-400 to-cyan-600',
    border: 'border-cyan-400',
    ring: 'ring-cyan-100',
  },
  red: {
    gradient: 'from-red-500 to-red-600',
    bg: 'bg-red-500',
    text: 'text-red-600',
    shadow: 'shadow-red-500/25',
    glow: 'group-hover:shadow-red-500/40',
    accent: 'bg-red-50 border-red-100',
    light: 'bg-red-50',
    handle: 'bg-gradient-to-br from-red-400 to-red-600',
    border: 'border-red-400',
    ring: 'ring-red-100',
  },
} as const satisfies Record<string, ColorConfig>;

export type NodeColor = keyof typeof COLOR_CLASSES;
