// supabase/functions/save-quiz-session/index.test.ts
//
// Unit tests for the two pure helpers extracted from save-quiz-session:
//
//   - pickUpdatableFields(session): mass-assignment filter + value
//     normalization. Strips PROTECTED_FIELDS (id, quiz_id, user_id,
//     session_token, created_at), keeps UPDATABLE_FIELDS only, clamps
//     numerics via the shared validators module, truncates strings
//     via MAX_NAME_LEN/MAX_EMAIL_LEN, clamps path_data via
//     clampPathData, and stamps updated_at.
//
//   - extractUserIdForRequest(req): best-effort extract of the caller's
//     user_id from the Authorization header. Returns null for anonymous
//     requests, malformed headers, or any Supabase error.
//
// Together these helpers gate every write to quiz_sessions — a bug in
// pickUpdatableFields would let an attacker mass-assign user_id or
// override session_token, and a bug in extractUserId would either
// silently grant ownership to anonymous calls or break legitimate
// users.
//
// Run with:
//   deno test --allow-read --allow-env supabase/functions/save-quiz-session/index.test.ts

import { assertEquals, assertExists, assertStringIncludes } from "https://deno.land/std@0.177.0/testing/asserts.ts";
import { extractUserIdForRequest, pickUpdatableFields } from "./index.ts";

// ---------------------------------------------------------------------------
// pickUpdatableFields — protected fields are stripped (mass-assignment guard)
// ---------------------------------------------------------------------------

Deno.test("pickUpdatableFields — id is stripped (PROTECTED)", () => {
  const out = pickUpdatableFields({
    id: "00000000-0000-0000-0000-000000000000",
    status: "in_progress",
  });
  assertEquals("id" in out, false);
});

Deno.test("pickUpdatableFields — quiz_id is stripped (PROTECTED)", () => {
  const out = pickUpdatableFields({
    quiz_id: "00000000-0000-0000-0000-000000000000",
    status: "in_progress",
  });
  assertEquals("quiz_id" in out, false);
});

Deno.test("pickUpdatableFields — user_id is stripped (PROTECTED, mass-assignment critical)", () => {
  // This is the most important guard: an attacker must not be able
  // to plant a session row claiming it belongs to another user.
  const out = pickUpdatableFields({
    user_id: "11111111-1111-1111-1111-111111111111",
    status: "in_progress",
  });
  assertEquals("user_id" in out, false);
});

Deno.test("pickUpdatableFields — session_token is stripped (PROTECTED, server-generated)", () => {
  // The token is generated by the server and returned to the client
  // once at session creation. Allowing the client to overwrite it
  // would defeat the ownership check.
  const out = pickUpdatableFields({
    session_token: "attacker-supplied-token",
    status: "in_progress",
  });
  assertEquals("session_token" in out, false);
});

Deno.test("pickUpdatableFields — created_at is stripped (PROTECTED, server-managed)", () => {
  const out = pickUpdatableFields({
    created_at: "2020-01-01T00:00:00Z",
    status: "in_progress",
  });
  assertEquals("created_at" in out, false);
});

// ---------------------------------------------------------------------------
// pickUpdatableFields — unknown fields are stripped
// ---------------------------------------------------------------------------

Deno.test("pickUpdatableFields — unknown column is dropped (defense vs. schema drift)", () => {
  const out = pickUpdatableFields({
    evil_column: "dropped",
    status: "in_progress",
  });
  assertEquals("evil_column" in out, false);
});

// ---------------------------------------------------------------------------
// pickUpdatableFields — value normalization
// ---------------------------------------------------------------------------

Deno.test("pickUpdatableFields — status not in ALLOWED_STATUS is removed", () => {
  const out = pickUpdatableFields({ status: "evil" });
  assertEquals("status" in out, false);
});

Deno.test("pickUpdatableFields — status 'in_progress' / 'completed' / 'abandoned' pass through", () => {
  for (const s of ["in_progress", "completed", "abandoned"]) {
    const out = pickUpdatableFields({ status: s });
    assertEquals(out.status, s);
  }
});

Deno.test("pickUpdatableFields — score is clamped to [0, MAX_SCORE]", () => {
  const maxOut = pickUpdatableFields({ score: 10_000_000 });
  // MAX_SCORE = 1_000_000 per _shared/validators.ts. The clamp caps at that.
  assertEquals(typeof maxOut.score, "number");
  assertEquals(maxOut.score as number, 1_000_000);

  const negOut = pickUpdatableFields({ score: -5 });
  assertEquals(negOut.score as number, 0);

  const fine = pickUpdatableFields({ score: 42 });
  assertEquals(fine.score as number, 42);
});

Deno.test("pickUpdatableFields — time_spent_seconds is clamped to [0, MAX_TIME_SECONDS]", () => {
  // MAX_TIME_SECONDS = 604_800 (1 week) per validators.
  const huge = pickUpdatableFields({ time_spent_seconds: 10_000_000_000 });
  assertEquals(huge.time_spent_seconds as number, 604_800);
  const neg = pickUpdatableFields({ time_spent_seconds: -1 });
  assertEquals(neg.time_spent_seconds as number, 0);
});

Deno.test("pickUpdatableFields — participant_name truncated to MAX_NAME_LEN (200)", () => {
  const long = "a".repeat(500);
  const out = pickUpdatableFields({ participant_name: long });
  assertExists(out.participant_name);
  assertEquals((out.participant_name as string).length, 200);
});

Deno.test("pickUpdatableFields — participant_email truncated to MAX_EMAIL_LEN (320)", () => {
  // RFC 5321 max email length is 320 (64 local + 1 @ + 255 domain).
  const long = "a".repeat(500) + "@example.com";
  const out = pickUpdatableFields({ participant_email: long });
  assertExists(out.participant_email);
  assertEquals((out.participant_email as string).length, 320);
});

Deno.test("pickUpdatableFields — updated_at is stamped", () => {
  const out = pickUpdatableFields({ status: "in_progress" });
  assertExists(out.updated_at);
  // ISO 8601 starts with year-month-day.
  assertStringIncludes(out.updated_at as string, "T");
});

// ---------------------------------------------------------------------------
// pickUpdatableFields — path_data clamp integration
// ---------------------------------------------------------------------------

Deno.test("pickUpdatableFields — path_data with > MAX_PATH_ELEMENTS is clamped", () => {
  // Phase 2 SQL hardening added a column-level CHECK
  // (array_length(path_data, 1) <= 1000). The pre-emptive clamp in
  // this function is the JS-side defense so legitimate long quizzes
  // can still save.
  const bigPath = Array.from({ length: 2000 }, (_, i) => ({ node: i }));
  const out = pickUpdatableFields({ path_data: bigPath });
  assertExists(out.path_data);
  // After clamp the array should be <= 1000 elements.
  const arr = out.path_data as unknown[];
  assertEquals(arr.length <= 1000, true);
});

// ---------------------------------------------------------------------------
// extractUserIdForRequest — header parsing
// ---------------------------------------------------------------------------

Deno.test("extractUserIdForRequest — no Authorization header → null (anonymous)", async () => {
  const req = new Request("https://example.com/");
  assertEquals(await extractUserIdForRequest(req), null);
});

Deno.test("extractUserIdForRequest — non-Bearer scheme → null", async () => {
  const req = new Request("https://example.com/", {
    headers: { Authorization: "Basic dXNlcjpwYXNz" },
  });
  assertEquals(await extractUserIdForRequest(req), null);
});

Deno.test("extractUserIdForRequest — 'Bearer ' with empty token → null", async () => {
  const req = new Request("https://example.com/", {
    headers: { Authorization: "Bearer " },
  });
  assertEquals(await extractUserIdForRequest(req), null);
});

Deno.test("extractUserIdForRequest — Bearer token but no SUPABASE_ANON_KEY → null", async () => {
  const snap = Deno.env.get("SUPABASE_ANON_KEY");
  try {
    Deno.env.delete("SUPABASE_ANON_KEY");
    const req = new Request("https://example.com/", {
      headers: { Authorization: "Bearer jwt.token.value" },
    });
    assertEquals(await extractUserIdForRequest(req), null);
  } finally {
    if (snap !== undefined) Deno.env.set("SUPABASE_ANON_KEY", snap);
  }
});
